// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkin.proto

package com.discursive.cjcook.proto;

public final class Checkin {
  private Checkin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PositionData extends
      com.google.protobuf.GeneratedMessage {
    // Use PositionData.newBuilder() to construct.
    private PositionData() {
      initFields();
    }
    private PositionData(boolean noInit) {}
    
    private static final PositionData defaultInstance;
    public static PositionData getDefaultInstance() {
      return defaultInstance;
    }
    
    public PositionData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.discursive.cjcook.proto.Checkin.internal_static_com_discursive_cjcook_proto_PositionData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.discursive.cjcook.proto.Checkin.internal_static_com_discursive_cjcook_proto_PositionData_fieldAccessorTable;
    }
    
    // required uint32 vehicle_id = 1;
    public static final int VEHICLE_ID_FIELD_NUMBER = 1;
    private boolean hasVehicleId;
    private int vehicleId_ = 0;
    public boolean hasVehicleId() { return hasVehicleId; }
    public int getVehicleId() { return vehicleId_; }
    
    // optional float latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private boolean hasLatitude;
    private float latitude_ = 0F;
    public boolean hasLatitude() { return hasLatitude; }
    public float getLatitude() { return latitude_; }
    
    // optional float longitude = 3;
    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private boolean hasLongitude;
    private float longitude_ = 0F;
    public boolean hasLongitude() { return hasLongitude; }
    public float getLongitude() { return longitude_; }
    
    // optional float altitude = 4 [default = 0];
    public static final int ALTITUDE_FIELD_NUMBER = 4;
    private boolean hasAltitude;
    private float altitude_ = 0F;
    public boolean hasAltitude() { return hasAltitude; }
    public float getAltitude() { return altitude_; }
    
    // optional int32 speed = 5;
    public static final int SPEED_FIELD_NUMBER = 5;
    private boolean hasSpeed;
    private int speed_ = 0;
    public boolean hasSpeed() { return hasSpeed; }
    public int getSpeed() { return speed_; }
    
    // optional uint64 timestamp = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional string status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasVehicleId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVehicleId()) {
        output.writeUInt32(1, getVehicleId());
      }
      if (hasLatitude()) {
        output.writeFloat(2, getLatitude());
      }
      if (hasLongitude()) {
        output.writeFloat(3, getLongitude());
      }
      if (hasAltitude()) {
        output.writeFloat(4, getAltitude());
      }
      if (hasSpeed()) {
        output.writeInt32(5, getSpeed());
      }
      if (hasTimestamp()) {
        output.writeUInt64(6, getTimestamp());
      }
      if (hasStatus()) {
        output.writeString(7, getStatus());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVehicleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getVehicleId());
      }
      if (hasLatitude()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getLatitude());
      }
      if (hasLongitude()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, getLongitude());
      }
      if (hasAltitude()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, getAltitude());
      }
      if (hasSpeed()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getSpeed());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, getTimestamp());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getStatus());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.discursive.cjcook.proto.Checkin.PositionData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.discursive.cjcook.proto.Checkin.PositionData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.discursive.cjcook.proto.Checkin.PositionData result;
      
      // Construct using com.discursive.cjcook.proto.Checkin.PositionData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.discursive.cjcook.proto.Checkin.PositionData();
        return builder;
      }
      
      protected com.discursive.cjcook.proto.Checkin.PositionData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.discursive.cjcook.proto.Checkin.PositionData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.discursive.cjcook.proto.Checkin.PositionData.getDescriptor();
      }
      
      public com.discursive.cjcook.proto.Checkin.PositionData getDefaultInstanceForType() {
        return com.discursive.cjcook.proto.Checkin.PositionData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.discursive.cjcook.proto.Checkin.PositionData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.discursive.cjcook.proto.Checkin.PositionData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.discursive.cjcook.proto.Checkin.PositionData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.discursive.cjcook.proto.Checkin.PositionData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.discursive.cjcook.proto.Checkin.PositionData) {
          return mergeFrom((com.discursive.cjcook.proto.Checkin.PositionData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.discursive.cjcook.proto.Checkin.PositionData other) {
        if (other == com.discursive.cjcook.proto.Checkin.PositionData.getDefaultInstance()) return this;
        if (other.hasVehicleId()) {
          setVehicleId(other.getVehicleId());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setVehicleId(input.readUInt32());
              break;
            }
            case 21: {
              setLatitude(input.readFloat());
              break;
            }
            case 29: {
              setLongitude(input.readFloat());
              break;
            }
            case 37: {
              setAltitude(input.readFloat());
              break;
            }
            case 40: {
              setSpeed(input.readInt32());
              break;
            }
            case 48: {
              setTimestamp(input.readUInt64());
              break;
            }
            case 58: {
              setStatus(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required uint32 vehicle_id = 1;
      public boolean hasVehicleId() {
        return result.hasVehicleId();
      }
      public int getVehicleId() {
        return result.getVehicleId();
      }
      public Builder setVehicleId(int value) {
        result.hasVehicleId = true;
        result.vehicleId_ = value;
        return this;
      }
      public Builder clearVehicleId() {
        result.hasVehicleId = false;
        result.vehicleId_ = 0;
        return this;
      }
      
      // optional float latitude = 2;
      public boolean hasLatitude() {
        return result.hasLatitude();
      }
      public float getLatitude() {
        return result.getLatitude();
      }
      public Builder setLatitude(float value) {
        result.hasLatitude = true;
        result.latitude_ = value;
        return this;
      }
      public Builder clearLatitude() {
        result.hasLatitude = false;
        result.latitude_ = 0F;
        return this;
      }
      
      // optional float longitude = 3;
      public boolean hasLongitude() {
        return result.hasLongitude();
      }
      public float getLongitude() {
        return result.getLongitude();
      }
      public Builder setLongitude(float value) {
        result.hasLongitude = true;
        result.longitude_ = value;
        return this;
      }
      public Builder clearLongitude() {
        result.hasLongitude = false;
        result.longitude_ = 0F;
        return this;
      }
      
      // optional float altitude = 4 [default = 0];
      public boolean hasAltitude() {
        return result.hasAltitude();
      }
      public float getAltitude() {
        return result.getAltitude();
      }
      public Builder setAltitude(float value) {
        result.hasAltitude = true;
        result.altitude_ = value;
        return this;
      }
      public Builder clearAltitude() {
        result.hasAltitude = false;
        result.altitude_ = 0F;
        return this;
      }
      
      // optional int32 speed = 5;
      public boolean hasSpeed() {
        return result.hasSpeed();
      }
      public int getSpeed() {
        return result.getSpeed();
      }
      public Builder setSpeed(int value) {
        result.hasSpeed = true;
        result.speed_ = value;
        return this;
      }
      public Builder clearSpeed() {
        result.hasSpeed = false;
        result.speed_ = 0;
        return this;
      }
      
      // optional uint64 timestamp = 6;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional string status = 7;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.discursive.cjcook.proto.PositionData)
    }
    
    static {
      defaultInstance = new PositionData(true);
      com.discursive.cjcook.proto.Checkin.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.discursive.cjcook.proto.PositionData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_discursive_cjcook_proto_PositionData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_discursive_cjcook_proto_PositionData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcheckin.proto\022\033com.discursive.cjcook.p" +
      "roto\"\216\001\n\014PositionData\022\022\n\nvehicle_id\030\001 \002(" +
      "\r\022\020\n\010latitude\030\002 \001(\002\022\021\n\tlongitude\030\003 \001(\002\022\023" +
      "\n\010altitude\030\004 \001(\002:\0010\022\r\n\005speed\030\005 \001(\005\022\021\n\tti" +
      "mestamp\030\006 \001(\004\022\016\n\006status\030\007 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_discursive_cjcook_proto_PositionData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_discursive_cjcook_proto_PositionData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_discursive_cjcook_proto_PositionData_descriptor,
              new java.lang.String[] { "VehicleId", "Latitude", "Longitude", "Altitude", "Speed", "Timestamp", "Status", },
              com.discursive.cjcook.proto.Checkin.PositionData.class,
              com.discursive.cjcook.proto.Checkin.PositionData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
